# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  ApplicationName: 'Pocket Calculator'

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages: 
- stage: Initialization
  jobs:
  - job: InitJob
    steps:
    - script: |
        echo
        echo Initializing $(ApplicationName)
        echo
        echo
        echo Installing Node.js
        echo 
        echo Show help for NYC
        npx nyc --help
#        echo Installing NYC
#        echo
#        npm i -D nyc  
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    displayName: 'Initializing'


- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo Building $(ApplicationName)
        echo For additional info see https://aka.ms/yaml
        npm run build
  displayName: 'Building'

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: |
        echo Testing $(ApplicationName)
        npm test
    displayName: 'Testing'

- stage: Audit
  jobs:
  - job: Audit
    steps:
    - script: |
        echo Auditing $(ApplicationName)
        npm audit
    displayName: 'Auditing'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying $(ApplicationName)
    displayName: 'Deploying'


